### Generate OTP for the given Phone Number
POST http://localhost:3000/api/auth/otp/generate
content-type: application/json

{
  "phoneNumber": "437-556-4035"
}

### Resend OTP for the given Phone Number
POST http://localhost:3000/api/auth/otp/resend
content-type: application/json

{
  "phoneNumber": "437-556-4035"
}

### Verify OPT
POST http://localhost:3000/api/auth/otp/verify
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "userOtp": "294275"
}

### Logout an user
GET http://localhost:3000/api/auth/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI2YjEyZTc4MTYxMWY2MDYwYTdhNzciLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjQ3MTcyNywiZXhwIjoxNzA5MDYzNzI3fQ.RlW_Y6b8GqisyTbC6C-8tjGL5J2886P07-03VnG7kuU

### Signup an user
POST http://localhost:3000/api/auth/user/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNzNmNWU0MGFkZDk1MThmMGI0NDIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjcxODE5NywiZXhwIjoxNzA5MzEwMTk3fQ.fB4LEtKwW4v-4--meNBhf4RHmheSp-0OInfcgIvGKyQ
content-type: application/json

{
  "email": "svijayr007@gmail.com",
  "firstName": "Vijay",
  "lastName": "vijay"
}

### Update User profile
PUT http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4NGRmZmI5ZmU1MWU3Nzc4ZGFlMDEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjU3ODU4MywiZXhwIjoxNzA5MTcwNTgzfQ.Qyz9zLvELlw7kpUJ9TzIJCqAPwQvnTWJjYMJIk-j_90
content-type: application/json

{
  "email": "derryckdxd@gmail.com",
  "firstName": "Derryck",
  "lastName": "Dowuona"
}

### Refresh Tokens - MUST SEND REFRESH TOKEN GENERATED BY VERIFY
GET http://localhost:3000/api/auth/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI2YjgwOGFiNjQ1YjU4ZjY0ODgwZjEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjU0Mjk1MiwiZXhwIjoxNzE5NTAyOTUyfQ.WXhioiBIUVS_-4WY2V8hGS6myQoGXJmPqvZv4ZgXtfI

### Update User Current Location
PATCH http://localhost:3000/api/auth/user/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNzNmNWU0MGFkZDk1MThmMGI0NDIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjcxODE5NywiZXhwIjoxNzA5MzEwMTk3fQ.fB4LEtKwW4v-4--meNBhf4RHmheSp-0OInfcgIvGKyQ
content-type: application/json

{
  "longitude": -80.5579867,
  "latitude": 43.4347027
}


### get Current User
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5ZDE4ZDg3MjNmNjQ2MDFiOTBmZGEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjY3NjYyMSwiZXhwIjoxNzA5MjY4NjIxfQ.jQsCrlcyOF1DFQ80am_Ca6CmHMTB-k-JKTU8Se2rEp8