### Generate OTP for the given Phone Number
POST http://localhost:3000/api/auth/otp/generate
content-type: application/json

{
  "phoneNumber": "437-556-4035"
}

### Resend OTP for the given Phone Number
POST http://localhost:3000/api/auth/otp/resend
content-type: application/json

{
  "phoneNumber": "437-556-4035"
}

### Verify OPT
POST http://localhost:3000/api/auth/otp/verify
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "userOtp": "162191"
}

### Logout an user
GET http://localhost:3000/api/auth/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJmZmU4M2NlZDI2NDg4NjcwMDc2N2EiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNzA4MTM0NywiZXhwIjoxNzA5NjczMzQ3fQ.p-9_Os3zVFIRbkvVpjBYDc-A259BoSGBhalSJYaaTEA

### Signup an user
POST http://localhost:3000/api/auth/user/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJmZmU4M2NlZDI2NDg4NjcwMDc2N2EiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNzA4MTYxMywiZXhwIjoxNzA5NjczNjEzfQ.AEoJsD_22y2IqtRs0rEtVwf0lysrx7XN1Uw2naVJnvs
content-type: application/json

{
  "email": "svijayr007@gmail.com",
  "firstName": "Vijay",
  "lastName": "vijay"
}

### Update User profile
PUT http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4NGRmZmI5ZmU1MWU3Nzc4ZGFlMDEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjU3ODU4MywiZXhwIjoxNzA5MTcwNTgzfQ.Qyz9zLvELlw7kpUJ9TzIJCqAPwQvnTWJjYMJIk-j_90
content-type: application/json

{
  "email": "derryckdxd@gmail.com",
  "firstName": "Derryck",
  "lastName": "Dowuona"
}

### Refresh Tokens - MUST SEND REFRESH TOKEN GENERATED BY VERIFY
GET http://localhost:3000/api/auth/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJmZmU4M2NlZDI2NDg4NjcwMDc2N2EiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNzA4MTM0NywiZXhwIjoxNzIwMDQxMzQ3fQ.9nJ6b6f_bjG_sXrl4KtDvM-T0AiRKfoT5cAEbEbmoys

### Update User Current Location
PATCH http://localhost:3000/api/auth/user/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJmZTU4ZTM1ODdkMGQyZDI3NTJhMWIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNzA3NDk1OCwiZXhwIjoxNzA5NjY2OTU4fQ.IlsnVFlHlNdSDq69JF6SPLP0bCqktGF-Pa_JGuKOidg
content-type: application/json

{
  "longitude": -80.5579867,
  "latitude": 43.4347027
}


### get Current User
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5ZDE4ZDg3MjNmNjQ2MDFiOTBmZGEiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcwNjY3NjYyMSwiZXhwIjoxNzA5MjY4NjIxfQ.jQsCrlcyOF1DFQ80am_Ca6CmHMTB-k-JKTU8Se2rEp8